blank_issues_enabled: false
contact_links:
  - name: RefindPlus Discussions
    url: https://github.com/RefindPlusRepo/RefindPlus/discussions/categories/general
    about: General Queries, Comments and/or Discussion
